export const orderConstants = {

    ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
    ADD_ORDER_SUCCESS: ' ADD_ORDER_SUCCESS',
    ADD_ORDER_FAILURE: '   ADD_ORDER_FAILURE',

    GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST',
    GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
    GET_ORDERS_FAILURE: ' GET_ORDERS_FAILURE'





}


