export const productConstants = {

    GET_PRODUCT_BY_ID_REQUEST: 'GET_PRODUCT_BY_ID_REQUEST',
    GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
    GET_PRODUCT_BY_ID_FAILURE: 'GET_PRODUCT_BY_ID_FAILURE',

    GET_PRODUCTS_REQUEST: ' GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: ' GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',



    ADD_PRODUCT_REQUEST: ' ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: '  ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: ' ADD_PRODUCT_FAILURE'



}


