export const productConstants = {

    GET_PRODUCT_BY_ID_REQUEST: ' GET_PRODUCT_BY_ID_REQUEST',
    GET_PRODUCT_BY_ID_SUCCESS: ' GET_PRODUCT_BY_ID_SUCCESS',
    GET_PRODUCT_BY_ID_FAILURE: ' GET_PRODUCT_BY_ID_FAILURE',

    GET_PRODUCTS_REQUEST: ' GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: ' GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: ' GET_PRODUCTS_FAILURE',



    ADD_PRODUCT_REQUEST: ' ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: ' ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: ' ADD_PRODUCT_FAILURE',

    DELETE_PRODUCT_REQUEST: ' DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: ' DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: ' DELETE_PRODUCT_FAILURE',

    UPDATE_PRODUCT_REQUEST: ' UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS: ' UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: ' UPDATE_PRODUCT_FAILURE',

    GET_PRODUCTS_N_REQUEST: ' GET_PRODUCTS_N_REQUEST',
    GET_PRODUCTS_N_SUCCESS: ' GET_PRODUCTS_N_SUCCESS',
    GET_PRODUCTS_N_FAILURE: ' GET_PRODUCTS_N_FAILURE'



}


